// This file will be auto-generated by Supabase CLI after schema is created.
// For now, we define the core types manually to enable type-safe development.

export type MembershipTier = "individual" | "corporate" | "emerging";

export type ApplicationStatus =
  | "pending"
  | "under_review"
  | "approved"
  | "rejected";

export type ChapterStatus = "active" | "in_formation";

export type EventType =
  | "general_meeting"
  | "seminar"
  | "webinar"
  | "networking"
  | "social"
  | "design_showcase"
  | "national";

export type RegistrationStatus =
  | "registered"
  | "attended"
  | "cancelled"
  | "waitlisted";

export type ChapterRole =
  | "member"
  | "committee_member"
  | "committee_chair"
  | "director_marketing"
  | "director_programs"
  | "director_membership"
  | "treasurer"
  | "secretary"
  | "vice_president"
  | "president";

export type NationalRole =
  | "national_board_member"
  | "national_treasurer"
  | "national_secretary"
  | "national_vice_president"
  | "national_president"
  | "national_advisor"
  | "staff";

export type CommitteeType =
  | "education"
  | "communications"
  | "membership"
  | "chapter_formation"
  | "awards"
  | "community_development";

export type VideoAccessLevel = "member" | "board" | "national";

export type ProjectScopeType = "chapter" | "national";

export type AnnouncementScopeType = "chapter" | "national";

export type VendorCategory =
  | "event_planner"
  | "decor"
  | "cake_designer"
  | "caterer"
  | "dj"
  | "florist"
  | "entertainment"
  | "hotelier"
  | "invitation"
  | "musician"
  | "officiant"
  | "photographer"
  | "rental"
  | "venue"
  | "videographer"
  | "other";

export const VENDOR_CATEGORY_LABELS: Record<VendorCategory, string> = {
  event_planner: "Event Planner",
  decor: "Decor",
  cake_designer: "Cake Designer",
  caterer: "Caterer",
  dj: "DJ",
  florist: "Florist",
  entertainment: "Entertainment",
  hotelier: "Hotelier",
  invitation: "Invitations",
  musician: "Musician",
  officiant: "Officiant",
  photographer: "Photographer",
  rental: "Rental Company",
  venue: "Venue",
  videographer: "Videographer",
  other: "Other",
};

export const CHAPTER_ROLE_LABELS: Record<ChapterRole, string> = {
  member: "Member",
  committee_member: "Committee Member",
  committee_chair: "Committee Chair",
  director_marketing: "Director of Marketing",
  director_programs: "Director of Programs",
  director_membership: "Director of Membership",
  treasurer: "Treasurer",
  secretary: "Secretary",
  vice_president: "Vice President",
  president: "President",
};

export const NATIONAL_ROLE_LABELS: Record<NationalRole, string> = {
  national_board_member: "National Board Member",
  national_treasurer: "National Treasurer",
  national_secretary: "National Secretary",
  national_vice_president: "National Vice President",
  national_president: "National President",
  national_advisor: "National Advisor",
  staff: "WIPA Staff",
};

// Board-level roles that grant access to the board collaboration tool
export const BOARD_ROLES: ChapterRole[] = [
  "director_marketing",
  "director_programs",
  "director_membership",
  "treasurer",
  "secretary",
  "vice_president",
  "president",
];

export function isBoardRole(role: ChapterRole): boolean {
  return BOARD_ROLES.includes(role);
}

export function isNationalRole(role: NationalRole): boolean {
  return !!role;
}
